  
dependencies:
  - click
  - fiona
  - gdal
  - geopy
  - joblib
  - matplotlib
  - netCDF4
  - numba
  - pandas
  - pyparsing
  - rasterio
  - r-lme4
  - rpy2
  - shapely
  - xlrd
  - pip:
    - pylru
    
